---

- name:
  apt_repository:
    repo: deb http://packages.elastic.co/logstash/2.2/debian stable main
    state: present
    filename: "logstash-2.2.x"
    update_cache: yes
  become: true
  become_user: root

- name: install package logstash
  apt:
    name: logstash
    update_cache: yes
  become: true
  become_user: root


